name: 'deploy'
on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Start OpenSCAD'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: Render and build OpenSCAD project
        uses: flat35hd99/eval-openscad@v0.1
        with:
          command: 'openscad -o "mx-flat-square.stl" "mx-flat-square.scad"'
